export const paths = {
  home: "/",
  login: "/login",
  register: "/register",
  menu: "/menu",
  clients: "/clients",
  owners: "/owners",
  suppliers: "/suppliers",
  employees: "/employees",
  houses: "/houses",
  sales: "/sales",
  financial: "/financial",
  dashboardConsolidacao: "/dashboard-consolidacao",
  dashboardProcessos: "/dashboard-processos",
};
