export const paths = {
  home: "/",
  login: "/login",
  register: "/register",
  profile: "/profile",
  settings: "/settings",
  clients: "/clients",
  owners: "/owners",
  suppliers: "/suppliers",
  employees: "/employees",
  houses: "/houses",
  sales: "/sales",
  financial: "/financial",
  notifications: "/notifications",
  nfe: "/nfe",
  dashboardConsolidacao: "/dashboard-consolidacao",
  dashboardProcessos: "/dashboard-processos",
  dashboardGoals: "/dashboard-metas",
  dashboardEstatisticas: "/dashboard-estatisticas",
};
